version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular*"
          - "ng-packagr"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "@angular-eslint/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
